CREATE TYPE "DealLossReason" AS ENUM (
  'NO_INTEREST',
  'PRICE_EXPECTATION',
  'BOUGHT_ELSEWHERE',
  'NO_RESPONSE',
  'VEHICLE_UNAVAILABLE',
  'OTHER'
);

ALTER TYPE "DealHistoryField" ADD VALUE IF NOT EXISTS 'LOSS_REASON';

ALTER TABLE "Deal"
  ADD COLUMN "lossReason" "DealLossReason";
